//
//  ConfigurationProtocols.swift
//  Practica_TEMPORIZADOR
//
//  Created Administrator on 06/07/23.
//  Copyright © 2023 ___ORGANIZATIONNAME___. All rights reserved.
//
//  Template generated by Juanpe Catalán @JuanpeCMiOS
//

import Foundation

//MARK: Wireframe -
protocol ConfigurationWireframeProtocol: AnyObject {

}
//MARK: Presenter -
protocol ConfigurationPresenterProtocol: AnyObject {

}

//MARK: Interactor -
protocol ConfigurationInteractorProtocol: AnyObject {

  var presenter: ConfigurationPresenterProtocol?  { get set }
}

//MARK: View -
protocol ConfigurationViewProtocol: AnyObject {

  var presenter: ConfigurationPresenterProtocol?  { get set }
}
