//
//  ConfigurationInteractor.swift
//  Practica_TEMPORIZADOR
//
//  Created Administrator on 06/07/23.
//  Copyright © 2023 ___ORGANIZATIONNAME___. All rights reserved.
//
//  Template generated by Juanpe Catalán @JuanpeCMiOS
//

import UIKit

class ConfigurationInteractor {
    //MARK: - Protocol Properties
    weak var presenter: ConfigurationPresenterProtocol?
}

//MARK: - Interactor Methods
extension ConfigurationInteractor: ConfigurationInteractorProtocol {
    
}
