//
//  ComentariosViewController.swift
//  Practica_TEMPORIZADOR
//
//  Created Administrator on 06/07/23.
//  Copyright © 2023 ___ORGANIZATIONNAME___. All rights reserved.
//
//  Template generated by Juanpe Catalán @JuanpeCMiOS
//

import UIKit

class ComentariosViewController: UIViewController {

    //MARK: - Protocol Properties
	var presenter: ComentariosPresenterProtocol?

    //MARK: - Properties
    
    //MARK: - Life Cycle
	override func viewDidLoad() {
        super.viewDidLoad()
        title = "comentarios"
        view.backgroundColor = .systemPink
    }
    
    //MARK: - Methods
}

//MARK: - View Methods
extension ComentariosViewController: ComentariosViewProtocol {
    
}

//MARK: - Private functions
extension ComentariosViewController {
    
}
