//
//  ComentariosRouter.swift
//  Practica_TEMPORIZADOR
//
//  Created Administrator on 06/07/23.
//  Copyright © 2023 ___ORGANIZATIONNAME___. All rights reserved.
//
//  Template generated by Juanpe Catalán @JuanpeCMiOS
//

import UIKit

class ComentariosRouter {
    //MARK: - Protocol Properties
    weak var viewController: UIViewController?
    
    //MARK: - Static Methods
    static func createModule() -> UIViewController {
        // Change to get view from storyboard if not using progammatic UI
        let view = ComentariosViewController(nibName: nil, bundle: nil)
        let interactor = ComentariosInteractor()
        let router = ComentariosRouter()
        let presenter = ComentariosPresenter(interface: view, interactor: interactor, router: router)
        
        view.presenter = presenter
        interactor.presenter = presenter
        router.viewController = view
        
        return view
    }
}

//MARK: - Router Metods
extension ComentariosRouter: ComentariosWireframeProtocol {
    
}

//MARK: - Private functions
extension ComentariosRouter {
    
}
