//
//  ComentariosPresenter.swift
//  Practica_TEMPORIZADOR
//
//  Created Administrator on 06/07/23.
//  Copyright © 2023 ___ORGANIZATIONNAME___. All rights reserved.
//
//  Template generated by Juanpe Catalán @JuanpeCMiOS
//

import UIKit

class ComentariosPresenter {
    //MARK: - Protocol Properties
    weak private var view: ComentariosViewProtocol?
    var interactor: ComentariosInteractorProtocol?
    private let router: ComentariosWireframeProtocol

    //MARK: - Life Cycle
    init(interface: ComentariosViewProtocol, interactor: ComentariosInteractorProtocol?, router: ComentariosWireframeProtocol) {
        self.view = interface
        self.interactor = interactor
        self.router = router
    }
}

//MARK: - Presenter Methods
extension ComentariosPresenter: ComentariosPresenterProtocol {
    
}

//MARK: - Private functions
extension ComentariosPresenter {
    
}
