//
//  ComentariosProtocols.swift
//  Practica_TEMPORIZADOR
//
//  Created Administrator on 06/07/23.
//  Copyright © 2023 ___ORGANIZATIONNAME___. All rights reserved.
//
//  Template generated by Juanpe Catalán @JuanpeCMiOS
//

import Foundation

//MARK: Wireframe -
protocol ComentariosWireframeProtocol: AnyObject {

}
//MARK: Presenter -
protocol ComentariosPresenterProtocol: AnyObject {

}

//MARK: Interactor -
protocol ComentariosInteractorProtocol: AnyObject {

  var presenter: ComentariosPresenterProtocol?  { get set }
}

//MARK: View -
protocol ComentariosViewProtocol: AnyObject {

  var presenter: ComentariosPresenterProtocol?  { get set }
}
