//
//  HomePresenter.swift
//  Practica_TEMPORIZADOR
//
//  Created Administrator on 05/07/23.
//  Copyright © 2023 ___ORGANIZATIONNAME___. All rights reserved.
//
//  Template generated by Juanpe Catalán @JuanpeCMiOS
//

import UIKit

class HomePresenter {
    //MARK: - Protocol Properties
    weak private var view: HomeViewProtocol?
    var interactor: HomeInteractorProtocol?
    private let router: HomeWireframeProtocol

    //MARK: - Life Cycle
    init(interface: HomeViewProtocol, interactor: HomeInteractorProtocol?, router: HomeWireframeProtocol) {
        self.view = interface
        self.interactor = interactor
        self.router = router
    }
}

//MARK: - Presenter Methods
extension HomePresenter: HomePresenterProtocol {
    func sendData(dato: Int) {
        view?.sendData(dato: dato)
    }
    
    func comentariosVc() {
        router.comentariosVc()
    }
    
    func configurationVc() {
        router.configurationVc()
    }
    
    
}

//MARK: - Private functions
extension HomePresenter {
    
}
