//
//  HomeInteractor.swift
//  Practica_TEMPORIZADOR
//
//  Created Administrator on 05/07/23.
//  Copyright © 2023 ___ORGANIZATIONNAME___. All rights reserved.
//
//  Template generated by Juanpe Catalán @JuanpeCMiOS
//

import UIKit

class HomeInteractor {
    //MARK: - Protocol Properties
    weak var presenter: HomePresenterProtocol?
}

//MARK: - Interactor Methods
extension HomeInteractor: HomeInteractorProtocol {
    func sendData(dato: Int) {
        presenter?.sendData(dato: dato)
    }
    
    
}
