//
//  HomeViewController.swift
//  Practica_TEMPORIZADOR
//
//  Created Administrator on 05/07/23.
//  Copyright © 2023 ___ORGANIZATIONNAME___. All rights reserved.
//
//  Template generated by Juanpe Catalán @JuanpeCMiOS
//

import UIKit

class HomeViewController: UIViewController {

    //MARK: - Protocol Properties
	var presenter: HomePresenterProtocol?

    //MARK: - Properties
    
    //MARK: - Life Cycle
	override func viewDidLoad() {
        super.viewDidLoad()
    }
    
    //MARK: - Methods
}

//MARK: - View Methods
extension HomeViewController: HomeViewProtocol {
    
}

//MARK: - Private functions
extension HomeViewController {
    
}
