//
//  HomeProtocols.swift
//  Practica_TEMPORIZADOR
//
//  Created Administrator on 05/07/23.
//  Copyright © 2023 ___ORGANIZATIONNAME___. All rights reserved.
//
//  Template generated by Juanpe Catalán @JuanpeCMiOS
//

import Foundation

//MARK: Wireframe -
protocol HomeWireframeProtocol: AnyObject {

}
//MARK: Presenter -
protocol HomePresenterProtocol: AnyObject {

}

//MARK: Interactor -
protocol HomeInteractorProtocol: AnyObject {

  var presenter: HomePresenterProtocol?  { get set }
}

//MARK: View -
protocol HomeViewProtocol: AnyObject {

  var presenter: HomePresenterProtocol?  { get set }
}
